# Generated by Django 3.2.7 on 2022-01-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name', max_length=40)),
                ('last_name', models.CharField(help_text='Last name', max_length=40)),
            ],
        ),
    ]
